### ISSUE TITLE
Impossible to configurate the module : 404

### ISSUE THREAD

**Issue by jbpotokar** [imaginary-cloud/redmine_risk_management#1]
Hello,

I've been trying to install on my redmine 2.6.1, by unzipping, changing rights, rake, and restart. 
All seems ok, except when I enter the interface andlist plugins. I choose redmine_risk_management configuration, and get a 404. 
Any idea on what I did wrong ? 

Regards

**Comment by gamafranco** [comment]
Hi @jbpotokar 

Thanks for the report.

What version of Redmine is on your setup?

Thanks!

**Comment by jbpotokar** [comment]
It's 2.6.1.

**Comment by Sousa5** [comment]
Hi @jbpotokar 
This issue has been fixed on version 0.4.

Thanks.
