### ISSUE TITLE
Configuration page is not opening (fails with Internal error)

### ISSUE THREAD

**Issue by twr7** [imaginary-cloud/redmine_risk_management#2]
Hi,

I tried the plugin and it doesn't work for me. From the logs it is clear why, but I am not sure what to do to fix it. Maybe I missed some step during installation!?

I am using
Environment:
  Redmine version                2.6.0.stable

_Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error._

From log file.
_Started GET "/settings/plugin/redmine_risk_management" for X at 2016-08-09 14:09:25 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_risk_management"}
  Current user: admin (id=1)
  Rendered plugins/redmine_risk_management/app/views/settings/risks/_status.html.erb (15.1ms)
  Rendered common/_tabs.html.erb (17.3ms)
  Rendered plugins/redmine_risk_management/app/views/settings/_risks.html.erb (26.9ms)
  Rendered settings/plugin.html.erb within layouts/admin (28.9ms)
Completed 500 Internal Server Error in 43.0ms

ActionView::Template::Error (Mysql2::Error: Table 'tredmine.risk_statuses' doesn't exist: SHOW FULL FIELDS FROM `risk_statuses`):
    18:   </thead>
    19: 
    20:   <tbody>
    21:   <% for risk_status in RiskStatus.ordered %>
    22:     <tr class="<%= cycle("odd", "even") %>">
    23:       <td class='name'>
    24:         <span class='color' style="background-color: <%= risk_status.color_name %>;"></span>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__1694197347127572683_70122693482020'
  app/views/common/_tabs.html.erb:21:in`each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__1694197347127572683_70122693482020'
  app/helpers/application_helper.rb:328:in`render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___3436024607453856647_70122690414980'
  app/views/settings/plugin.html.erb:4:in`_app_views_settings_plugin_html_erb___3436024607453856647_70122690414980'_

**Comment by danini-the-panini** [comment]
@twr7 
Have you run `rake redmine:plugins NAME=redmine_risk_management`?
This should run the migrations for the plugin and create the required tables for you.

**Comment by Sousa5** [comment]
Hi @twr7 

As @jellymann said you need to run `rake redmine:plugins NAME=redmine_risk_management` to create all the required tables.
If you have more problems with the installation fell free to check our installation guide.

Thanks
